apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  type: NodePort
  selector:
    app: front-app
  ports:
    - protocol: TCP
      port: 80             # Port du service
      targetPort: 80       # Port utilisé dans le conteneur
      nodePort: 30517        # Port accessible via minikube (facultatif)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-app
  template:
    metadata:
      labels:
        app: front-app
    spec:
      containers:
      - name: frontend-container
        image: angevirus/frontend:vf
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "150m"
          limits:
            memory: "256Mi"
            cpu: "500m"
